### ISSUE TITLE
After the system was upgraded to 10.12.6, the Mac OSX speed decreased significantly

### ISSUE THREAD

**Issue by nosize** [al3xtjames/Gigabyte-GA-Z77X-macOS-Install#67]
**System information**
 - macOS 10.12.6
 - GA-Z77X macOS Install v2.0.8
 - GA-Z77X-UD5H
 - Intel Core i7-3770K
 - NVIDIA GeForce GTX 970

Tried to install a clean system, did not help

**Comment by al3xtjames** [comment]
The XCPM patches need to be updated for 10.12.6. I'll push an update later today to fix this.

**Comment by nosize** [comment]
Thanks!

**Comment by al3xtjames** [comment]
This is fixed in v2.0.9.

**Comment by SebaARG** [comment]
**System information**

macOS 10.12.6
GA-Z77X macOS Install v2.0.9
GA-Z77X-UD5H
Intel Core i7-3770K
NVIDIA GeForce GTX 970

**Issue Description**

Hi! I fix the 800 MHz on  the XCPM patches but I can't update with GA-Z77X.sh script on my USB Install Media, I receive the following message

![captura de pantalla 2017-07-22 a la s 18 11 22](https://user-images.githubusercontent.com/28956345/28494828-58a632b6-6f10-11e7-89eb-90dfa4a3c414.png)
