### ISSUE TITLE
'fatal: Not a git repository'

### ISSUE THREAD

**Issue by HagenBarz** [al3xtjames/Gigabyte-GA-Z77X-macOS-Install#69]
## System Information

 - OS: macOS 10.12.6
 - Script: GA-Z77X macOS Install v2.0.9
 - MB: GA-Z77X-UD5H
 - CPU: Intel Core i7-3770k
 - IGPU: Intel HD Graphics 4000
 - GIGABYTE GeForce GTX 680 / N/A

## Issue Type

 - [ ] I'm trying to boot the macOS installer
 - [ ] I'm trying to boot my macOS install

 - [x] I'm encountering errors during/after the post-install script

 - [ ] Can you add support for my board?

## Issue Description

bash -x ./GA-Z77X.sh --update
+ set -e
+ set -u
+ gScriptVersion=2.0.9
+ gStyleReset='\e[0m'
+ gStyleBold='\e[1m'
+ gStyleUnderlined='\e[4m'
+ gColorBlack='\e[1m'
+ gColorRed='\e[1;31m'
+ gColorGreen='\e[32m'
+ gColorDarkYellow='\e[33m'
+ gColorMagenta='\e[1;35m'
+ gColorPurple='\e[35m'
+ gColorCyan='\e[36m'
+ gColorBlue='\e[1;34m'
+ gColorOrange='\e[31m'
+ gColorGrey='\e[37m'
+++ dirname ./GA-Z77X.sh
++ cd .
++ pwd
+ gRepo='/Volumes/User/hagen/Downloads/GA Z77X UD5H/Sierra Stuff/Gigabyte-GA-Z77X-macOS-Install-master'
++ id -u
+ gID=501
++ sw_vers -productVersion
++ awk -F . '{print $1 "." $2}'
+ gOSVersion=10.12
++ sysctl -n machdep.cpu.brand_string
++ cut -d - -f 2
++ cut -c 1
+ gCoreBridgeType=3
+ gProductName=iMac13,2
+ '[' 1 -eq 1 ']'
+ case "$1" in
+ git_update
+ cd '/Volumes/User/hagen/Downloads/GA Z77X UD5H/Sierra Stuff/Gigabyte-GA-Z77X-macOS-Install-master'
+ git pull
fatal: Not a git repository (or any parent up to mount parent /Volume) Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by HagenBarz** [comment]
After searching the web I found a solution to get out of this error (using _git clone_ instead of _git co_). Now I run in a similar error as issue #68 .

+ set -e
+ set -u
+ gScriptVersion=2.0.9
+ gStyleReset='\e[0m'
+ gStyleBold='\e[1m'
+ gStyleUnderlined='\e[4m'
+ gColorBlack='\e[1m'
+ gColorRed='\e[1;31m'
+ gColorGreen='\e[32m'
+ gColorDarkYellow='\e[33m'
+ gColorMagenta='\e[1;35m'
+ gColorPurple='\e[35m'
+ gColorCyan='\e[36m'
+ gColorBlue='\e[1;34m'
+ gColorOrange='\e[31m'
+ gColorGrey='\e[37m'
+++ dirname ./GA-Z77X.sh
++ cd .
++ pwd
+ gRepo='/Volumes/User/hagen/Downloads/GA Z77X UD5H/Sierra Stuff/Gigabyte-GA-Z77X-macOS-Install'
++ id -u
+ gID=501
++ sw_vers -productVersion
++ awk -F . '{print $1 "." $2}'
+ gOSVersion=10.12
++ sysctl -n machdep.cpu.brand_string
++ cut -d - -f 2
++ cut -c 1
+ gCoreBridgeType=3
+ gProductName=iMac13,2
+ '[' 1 -eq 1 ']'
+ case "$1" in
+ git_update
+ cd '/Volumes/User/hagen/Downloads/GA Z77X UD5H/Sierra Stuff/Gigabyte-GA-Z77X-macOS-Install'
+ git pull
+ check_macos_version
+ case $gOSVersion in
+ check_motherboard
++ ioreg -k OEMBoard -p IODeviceTree
++ awk '/OEMBoard/ {print $4}'
++ tr -d '<"">'
+ local motherboard=Z77X-UD5H
+ case $motherboard in
+ gMotherboard=Z77X-UD5H
+ gLayoutID=3
+ check_root
++ id -u
+ '[' 501 -ne 0 ']'
+ printf 'This part of the script %bneeds%b to be run as root.\n' '\e[1m' '\e[0m'
+ sudo clear
Password:
+ install 1
++ '/Volumes/User/hagen/Downloads/GA Z77X UD5H/Sierra Stuff/Gigabyte-GA-Z77X-macOS-Install/acpi/build/tools/mount_efi'
+ gEFIMount=/Volumes/EFI
++ date '+%Y-%m-%d %Hh %Mm %Ss'
+ local 'date=2017-07-26 09h 08m 03s'
+ '[' 1 -eq 1 ']'
+ print_header '\e[1m--update: \e[32mUpdating Clover & kexts\e[0m'
++ echo Z77X-UD5H
++ cut -d - -f 1
+ local boardSeries=Z77X
++ echo UD5H
+ local board=UD5H
+ clear
+ echo 'Gigabyte GA-Z77X Series Post-Install Script v2.0.9 by theracermaster'
+ printf 'Updates & info: %bhttps://github.com/theracermaster/Gigabyte-GA-Z77X-macOS-Install%b\n' '\e[4m' '\e[0m'
+ echo --------------------------------------------------------------------------------
+ printf 'Detected motherboard: Gigabyte %bGA-%s-%b%s%b\n' '\e[1m' Z77X '\e[36m' UD5H '\e[0m'
+ printf 'Script arguments: ./GA-Z77X.sh \e[1m--update: \e[32mUpdating Clover & kexts\e[0m\n'
+ echo --------------------------------------------------------------------------------
+ mkdir -p '/Volumes/User/hagen/Downloads/GA Z77X UD5H/Sierra Stuff/Gigabyte-GA-Z77X-macOS-Install/backups/EFI (2017-07-26 09h 08m 03s)'
+ cp -R /Volumes/EFI/EFI/ '/Volumes/User/hagen/Downloads/GA Z77X UD5H/Sierra Stuff/Gigabyte-GA-Z77X-macOS-Install/backups/EFI (2017-07-26 09h 08m 03s)'
+ printf '%bCurrent EFI folder copied to:%b %bbackups/EFI (2017-07-26 09h 08m 03s)%b\n' '\e[1m' '\e[0m' '\e[4m' '\e[0m'
+ touch /Volumes/EFI/.metadata_never_index
+ mkdir -p /Volumes/EFI/EFI/BOOT
+ mkdir -p /Volumes/EFI/EFI/CLOVER/themes
+ cp '/Volumes/User/hagen/Downloads/GA Z77X UD5H/Sierra Stuff/Gigabyte-GA-Z77X-macOS-Install/efi/CLOVERX64.efi' /Volumes/EFI/EFI/BOOT/BOOTX64.efi
+ cp -R '/Volumes/User/hagen/Downloads/GA Z77X UD5H/Sierra Stuff/Gigabyte-GA-Z77X-macOS-Install/efi/themes' /Volumes/EFI/EFI/CLOVER
+ cp -R '/Volumes/User/hagen/Downloads/GA Z77X UD5H/Sierra Stuff/Gigabyte-GA-Z77X-macOS-Install/efi/tools' /Volumes/EFI/EFI/CLOVER
+ '[' 1 -eq 1 ']'
+ printf '%bUpdating config.plist%b:\n' '\e[1m' '\e[0m'
+ update_clover_config_dict :ACPI /Volumes/EFI/EFI/CLOVER/config.plist
++ mktemp
+ tmpConfig=/var/folders/cv/1xdt7m_d7m96lxj4yf2d7m1r0000gn/T/tmp.nK16ruhu
+ gen_clover_config /var/folders/cv/1xdt7m_d7m96lxj4yf2d7m1r0000gn/T/tmp.nK16ruhu
+ cp '/Volumes/User/hagen/Downloads/GA Z77X UD5H/Sierra Stuff/Gigabyte-GA-Z77X-macOS-Install/config/config_main.plist' /var/folders/cv/1xdt7m_d7m96lxj4yf2d7m1r0000gn/T/tmp.nK16ruhu
+ '[' 3 -eq 3 ']'
+ /usr/libexec/PlistBuddy -c 'Set '\'':ACPI:SSDT:PluginType'\'' 1' /var/folders/cv/1xdt7m_d7m96lxj4yf2d7m1r0000gn/T/tmp.nK16ruhu
+ /usr/libexec/PlistBuddy -c 'Merge /Volumes/User/hagen/Downloads/GA Z77X UD5H/Sierra Stuff/Gigabyte-GA-Z77X-macOS-Install/config/config_patches_ivy.plist :KernelAndKextPatches' /var/folders/cv/1xdt7m_d7m96lxj4yf2d7m1r0000gn/T/tmp.nK16ruhu
Merge: "Z77X" Entry Does Not Exist

**Comment by HagenBarz** [comment]
I've cloned the repo again but this time in my home directory and - abracadabra magic - all worked properly.

**Comment by al3xtjames** [comment]
Hmm, I was having trouble reproducing it. Quite strange though, I'll do some more checks.
